name: test bark

on:
  # 手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'test bark'

jobs:
  job:
    name: test bark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Push notification
        uses: shink/bark-action@v2
        continue-on-error: true
        with:
          key: ${{ secrets.BARK_KEY }} # Your secret key, it is required
          host: ${{ vars.BARK_HOST }} # Your Bark host, the default is 'https://api.day.app'
          title: Subscribe update!
          body: Qx and Clash config has be deployed on Github Gist
          sound: calypso
          isArchive: 1
          # url: https://yuanhaoji.com
          # automaticallyCopy: 1
          # copy: Content copied to clipboard
