name: youtube proxy

on:
  #github actions定时任务不稳定 改为vps定时任务
  repository_dispatch:
  # 手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'youtube proxy'

jobs:
  job:
    name: youtube proxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 设置python环境(v3.11)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 安装pip依赖(清华大学镜像源)
        run: pip install -r requirements.txt

      - name: pull
        run: |
          git checkout .
          git pull --allow-unrelated-histories

      - name: install google chrome browser
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 116.0.5797.0

      - name: check google chrome version
        run: chrome --version

      - name: update proxy
        run: |
          python youtube.py

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
