name: youtube proxy windows

on:
  #github actions定时任务不稳定 改为gcp定时任务 订阅主题: often-updated
  # repository_dispatch:
  # 手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'youtube proxy windows'

jobs:
  job:
    name: youtube proxy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 设置python环境(v3.11)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 安装pip依赖(清华大学镜像源)
        run: pip install -r requirements.txt

      - name: pull
        run: |
          git checkout .
          git pull --allow-unrelated-histories

      # - name: install chinese font
      #   run: |
      #     sudo mkdir -p /usr/share/fonts/chinese/
      #     sudo cp songti.ttf /usr/share/fonts/chinese/
      #     cd /usr/share/fonts/chinese/
      #     sudo fc-cache -fv
      #     sudo fc-list

      # ================youtube is not incompatible with google chrome, please change to firefox=========================
      # - uses: logikal-io/install-chrome@v1
      #   with:
      #     version: 113.0.5672.126-1

      # - name: check google chrome version
      #   run: |
      #     sudo ln -fs /opt/google/chrome/chrome /usr/bin/chrome
      #     sudo ln -fs /opt/google/chrome/chrome /usr/local/bin/chrome
      #     chrome --version
      # ================youtube is not incompatible with google chrome, please change to firefox=========================

      - name: install firefox broswer
        uses: browser-actions/setup-firefox@v1

      - name: check firefox chrome version
        run: firefox --version

      - name: install geckodriver
        run: |
          sudo mkdir -p /opt/chromedriver/
          cd /opt/chromedriver/
          sudo wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          sudo tar -zxvf geckodriver-v0.33.0-linux64.tar.gz
          sudo chmod 777 geckodriver

      - name: update proxy
        run: |
          python youtube.py

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
